/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Video_Management_Systems;

import java.applet.Applet;
import java.applet.AudioClip;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Random;
import javax.swing.*;
import java.awt.*;
import java.awt.print.PrinterException;
import java.io.File;
import java.net.URL;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.Clip;
import javax.sound.sampled.AudioSystem;

/**
 *
 * @author nickmccall
 */
public class Video_Management_System extends javax.swing.JFrame {
    double [] game = new double [6];
    double [] console = new double [7];
    double [] accesory = new double [5];
    String [] cost = new String [3];
    double [] i = new double[25];
    private int xCoor = 100;
    private Timer t;
    
    /**
     * Creates new form Video_Management_System
     */
    public Video_Management_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void playSound(String soundName)
 {
   try 
   {
   AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile( ));
   Clip clip = AudioSystem.getClip( );
   clip.open(audioInputStream);
   clip.start( );
   }
   catch(Exception ex)
   {
     System.out.println("Error with playing sound.");
     ex.printStackTrace( );
   }
 }
    
    public void paintComponent ( Graphics graphics ) {
        paintComponent(graphics);
        Graphics2D graphics2d = ( Graphics2D ) graphics;

        graphics.setColor ( Color.cyan );
        graphics2d.fillOval(xCoor, 2000, 2000, 2000);}
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jCheckBoxXboxOne = new javax.swing.JCheckBox();
        jTextFieldXboxOne = new javax.swing.JTextField();
        jCheckBoxSteam = new javax.swing.JCheckBox();
        jTextFieldSteam = new javax.swing.JTextField();
        jCheckBoxPS4 = new javax.swing.JCheckBox();
        jTextFieldPS4 = new javax.swing.JTextField();
        jCheckBoxWiiU = new javax.swing.JCheckBox();
        jTextFieldWii = new javax.swing.JTextField();
        jCheckBoxGamecube = new javax.swing.JCheckBox();
        jTextFieldGamecube = new javax.swing.JTextField();
        jCheckBoxXbox360 = new javax.swing.JCheckBox();
        jTextFieldXbox360 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jCheckBoxPS3 = new javax.swing.JCheckBox();
        jTextFieldPS3 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jCheckBoxHeadset = new javax.swing.JCheckBox();
        jTextFieldHeadset = new javax.swing.JTextField();
        jCheckBoxPS4Controller = new javax.swing.JCheckBox();
        jTextFieldPS4Controller = new javax.swing.JTextField();
        jCheckBoxWiiuGamepad = new javax.swing.JCheckBox();
        jTextFieldWiiugamepad = new javax.swing.JTextField();
        jCheckBoxGamecubeController = new javax.swing.JCheckBox();
        jTextFieldgamecubecontroller = new javax.swing.JTextField();
        jCheckBoxXboxOneController = new javax.swing.JCheckBox();
        jTextFieldxboxcontroller = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabelTax = new javax.swing.JLabel();
        jTextFieldTax = new javax.swing.JTextField();
        jLabelSubTotal = new javax.swing.JLabel();
        jTextFieldSubTotal = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jButtonJukeBox = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButtonTotal = new javax.swing.JButton();
        jButtonReceipt = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaReceipt = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        jCheckBoxMadden = new javax.swing.JCheckBox();
        jTextFieldMadden = new javax.swing.JTextField();
        jCheckBoxIW = new javax.swing.JCheckBox();
        jTextFieldWarfare = new javax.swing.JTextField();
        jCheckBoxWatchDogs = new javax.swing.JCheckBox();
        jTextFieldWatchDog = new javax.swing.JTextField();
        jCheckBoxMarioKart = new javax.swing.JCheckBox();
        jTextFieldMarioKart = new javax.swing.JTextField();
        jCheckBoxDota = new javax.swing.JCheckBox();
        jTextFieldDota = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jCheckBoxForza = new javax.swing.JCheckBox();
        jTextFieldForza = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabelCostConsole = new javax.swing.JLabel();
        jTextFieldCostConsole = new javax.swing.JTextField();
        jLabelCostGame = new javax.swing.JLabel();
        jTextFieldCostGame = new javax.swing.JTextField();
        jLabelCostAccesories = new javax.swing.JLabel();
        jTextFieldCostAccesories = new javax.swing.JTextField();

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 780));
        setSize(new java.awt.Dimension(1200, 780));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel4.add(jLabel1);

        Title.setFont(new java.awt.Font("Lucida Grande", 1, 72)); // NOI18N
        Title.setText("      Nick's Game Shop     ");
        jPanel4.add(Title);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel4.add(jLabel3);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1210, 140));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jCheckBoxXboxOne.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jCheckBoxXboxOne.setText("Xbox One");
        jCheckBoxXboxOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxXboxOneActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBoxXboxOne);

        jTextFieldXboxOne.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldXboxOne.setText("0");
        jTextFieldXboxOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldXboxOne.setPreferredSize(new java.awt.Dimension(100, 40));
        jTextFieldXboxOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldXboxOneActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldXboxOne);

        jCheckBoxSteam.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jCheckBoxSteam.setLabel("SteamBox");
        jCheckBoxSteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSteamActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBoxSteam);

        jTextFieldSteam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSteam.setText("0");
        jTextFieldSteam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldSteam.setPreferredSize(new java.awt.Dimension(100, 40));
        jTextFieldSteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSteamActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldSteam);

        jCheckBoxPS4.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jCheckBoxPS4.setLabel("PlayStation 4");
        jCheckBoxPS4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxPS4MouseClicked(evt);
            }
        });
        jCheckBoxPS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPS4ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBoxPS4);

        jTextFieldPS4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPS4.setText("0");
        jTextFieldPS4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldPS4.setPreferredSize(new java.awt.Dimension(100, 40));
        jTextFieldPS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPS4ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldPS4);

        jCheckBoxWiiU.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jCheckBoxWiiU.setLabel("Wii U");
        jCheckBoxWiiU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWiiUActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBoxWiiU);

        jTextFieldWii.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldWii.setText("0");
        jTextFieldWii.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldWii.setPreferredSize(new java.awt.Dimension(100, 40));
        jTextFieldWii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWiiActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldWii);

        jCheckBoxGamecube.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jCheckBoxGamecube.setLabel("Gamecube");
        jCheckBoxGamecube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGamecubeActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBoxGamecube);

        jTextFieldGamecube.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldGamecube.setText("0");
        jTextFieldGamecube.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldGamecube.setPreferredSize(new java.awt.Dimension(100, 40));
        jTextFieldGamecube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGamecubeActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldGamecube);

        jCheckBoxXbox360.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jCheckBoxXbox360.setText("Xbox 360");
        jCheckBoxXbox360.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxXbox360ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBoxXbox360);

        jTextFieldXbox360.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldXbox360.setText("0");
        jTextFieldXbox360.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldXbox360.setPreferredSize(new java.awt.Dimension(100, 40));
        jTextFieldXbox360.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldXbox360ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldXbox360);

        jTextField1.setBackground(new java.awt.Color(238, 238, 238));
        jTextField1.setForeground(new java.awt.Color(238, 238, 238));
        jTextField1.setText("           ");
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(238, 238, 238));
        jTextField1.setDisabledTextColor(new java.awt.Color(238, 238, 238));
        jTextField1.setSelectedTextColor(new java.awt.Color(238, 238, 238));
        jTextField1.setSelectionColor(new java.awt.Color(238, 238, 238));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField1);

        jCheckBoxPS3.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jCheckBoxPS3.setText("PS3");
        jCheckBoxPS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPS3ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBoxPS3);

        jTextFieldPS3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPS3.setText("0");
        jTextFieldPS3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldPS3.setPreferredSize(new java.awt.Dimension(100, 40));
        jTextFieldPS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPS3ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldPS3);

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 420, 400));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jCheckBoxHeadset.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxHeadset.setText("Turtle Beach Headset");
        jCheckBoxHeadset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHeadsetActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBoxHeadset);

        jTextFieldHeadset.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldHeadset.setText("0");
        jTextFieldHeadset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldHeadset.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldHeadset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHeadsetActionPerformed(evt);
            }
        });
        jPanel7.add(jTextFieldHeadset);

        jCheckBoxPS4Controller.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxPS4Controller.setText("PS4 Controller");
        jCheckBoxPS4Controller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPS4ControllerActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBoxPS4Controller);

        jTextFieldPS4Controller.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPS4Controller.setText("0");
        jTextFieldPS4Controller.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldPS4Controller.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldPS4Controller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPS4ControllerActionPerformed(evt);
            }
        });
        jPanel7.add(jTextFieldPS4Controller);

        jCheckBoxWiiuGamepad.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxWiiuGamepad.setText("Wii U Gamepad");
        jCheckBoxWiiuGamepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWiiuGamepadActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBoxWiiuGamepad);

        jTextFieldWiiugamepad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldWiiugamepad.setText("0");
        jTextFieldWiiugamepad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldWiiugamepad.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldWiiugamepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWiiugamepadActionPerformed(evt);
            }
        });
        jPanel7.add(jTextFieldWiiugamepad);

        jCheckBoxGamecubeController.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxGamecubeController.setText("Gamecube Controller");
        jCheckBoxGamecubeController.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGamecubeControllerActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBoxGamecubeController);

        jTextFieldgamecubecontroller.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldgamecubecontroller.setText("0");
        jTextFieldgamecubecontroller.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldgamecubecontroller.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldgamecubecontroller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldgamecubecontrollerActionPerformed(evt);
            }
        });
        jPanel7.add(jTextFieldgamecubecontroller);

        jCheckBoxXboxOneController.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxXboxOneController.setText("Xbox One Controller");
        jCheckBoxXboxOneController.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxXboxOneControllerActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBoxXboxOneController);

        jTextFieldxboxcontroller.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldxboxcontroller.setText("0");
        jTextFieldxboxcontroller.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldxboxcontroller.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldxboxcontroller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldxboxcontrollerActionPerformed(evt);
            }
        });
        jPanel7.add(jTextFieldxboxcontroller);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 390, 190));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabelTax.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabelTax.setText("Tax");
        jLabelTax.setAlignmentY(10.0F);
        jPanel8.add(jLabelTax);

        jTextFieldTax.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTax.setText("0");
        jTextFieldTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldTax.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTaxActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldTax);

        jLabelSubTotal.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabelSubTotal.setText("Sub-Total");
        jPanel8.add(jLabelSubTotal);

        jTextFieldSubTotal.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSubTotal.setText("0");
        jTextFieldSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldSubTotal.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSubTotalActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldSubTotal);

        jLabelTotal.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTotal.setText("Total");
        jPanel8.add(jLabelTotal);

        jTextFieldTotal.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTotal.setText("0");
        jTextFieldTotal.setToolTipText("");
        jTextFieldTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldTotal.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldTotal);

        jButtonJukeBox.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jButtonJukeBox.setText("JukeBox");
        jButtonJukeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJukeBoxActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonJukeBox);

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, 370, 140));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jButtonTotal.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jButtonTotal.setText("Total");
        jButtonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTotalActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonTotal);

        jButtonReceipt.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jButtonReceipt.setText("Receipt");
        jButtonReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceiptActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonReceipt);

        jButtonPrint.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jButtonPrint.setText("Print");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonPrint);

        jButtonReset.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonReset);

        jButtonExit.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Video_Management_Systems/explosion.gif"))); // NOI18N
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonExit);

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 590, 470, 130));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextAreaReceipt.setColumns(29);
        jTextAreaReceipt.setRows(24);
        jTextAreaReceipt.setTabSize(40);
        jTextAreaReceipt.setSize(new java.awt.Dimension(600, 600));
        jScrollPane1.setViewportView(jTextAreaReceipt);

        jPanel10.add(jScrollPane1);

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 380, 410));

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jCheckBoxMadden.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxMadden.setText("Madden 17 Xbox One");
        jCheckBoxMadden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMaddenActionPerformed(evt);
            }
        });
        jPanel12.add(jCheckBoxMadden);

        jTextFieldMadden.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMadden.setText("0");
        jTextFieldMadden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldMadden.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldMadden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaddenActionPerformed(evt);
            }
        });
        jPanel12.add(jTextFieldMadden);

        jCheckBoxIW.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxIW.setText("Infinite Warfare PS4");
        jCheckBoxIW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxIWActionPerformed(evt);
            }
        });
        jPanel12.add(jCheckBoxIW);

        jTextFieldWarfare.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldWarfare.setText("0");
        jTextFieldWarfare.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldWarfare.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldWarfare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWarfareActionPerformed(evt);
            }
        });
        jPanel12.add(jTextFieldWarfare);

        jCheckBoxWatchDogs.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxWatchDogs.setText("Watch Dogs Wii U");
        jCheckBoxWatchDogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWatchDogsActionPerformed(evt);
            }
        });
        jPanel12.add(jCheckBoxWatchDogs);

        jTextFieldWatchDog.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldWatchDog.setText("0");
        jTextFieldWatchDog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldWatchDog.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldWatchDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWatchDogActionPerformed(evt);
            }
        });
        jPanel12.add(jTextFieldWatchDog);

        jCheckBoxMarioKart.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxMarioKart.setText("Mario Kart GameCube");
        jCheckBoxMarioKart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMarioKartActionPerformed(evt);
            }
        });
        jPanel12.add(jCheckBoxMarioKart);

        jTextFieldMarioKart.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMarioKart.setText("0");
        jTextFieldMarioKart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldMarioKart.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldMarioKart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMarioKartActionPerformed(evt);
            }
        });
        jPanel12.add(jTextFieldMarioKart);

        jCheckBoxDota.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxDota.setText("Dota 2");
        jCheckBoxDota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDotaActionPerformed(evt);
            }
        });
        jPanel12.add(jCheckBoxDota);

        jTextFieldDota.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDota.setText("0");
        jTextFieldDota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldDota.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldDota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDotaActionPerformed(evt);
            }
        });
        jPanel12.add(jTextFieldDota);

        jTextField2.setBackground(new java.awt.Color(238, 238, 238));
        jTextField2.setForeground(new java.awt.Color(238, 238, 238));
        jTextField2.setText("           ");
        jTextField2.setBorder(null);
        jTextField2.setCaretColor(new java.awt.Color(238, 238, 238));
        jTextField2.setDisabledTextColor(new java.awt.Color(238, 238, 238));
        jTextField2.setSelectedTextColor(new java.awt.Color(238, 238, 238));
        jTextField2.setSelectionColor(new java.awt.Color(238, 238, 238));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel12.add(jTextField2);

        jCheckBoxForza.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxForza.setText("Forza 3 Xbox One");
        jCheckBoxForza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxForzaActionPerformed(evt);
            }
        });
        jPanel12.add(jCheckBoxForza);

        jTextFieldForza.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldForza.setText("0");
        jTextFieldForza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldForza.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldForza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldForzaActionPerformed(evt);
            }
        });
        jPanel12.add(jTextFieldForza);

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 390, 210));

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabelCostConsole.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabelCostConsole.setText("Cost of Consoles");
        jPanel14.add(jLabelCostConsole);

        jTextFieldCostConsole.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCostConsole.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCostConsole.setText("0");
        jTextFieldCostConsole.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldCostConsole.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldCostConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCostConsoleActionPerformed(evt);
            }
        });
        jPanel14.add(jTextFieldCostConsole);

        jLabelCostGame.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabelCostGame.setText("Cost Of Games");
        jPanel14.add(jLabelCostGame);

        jTextFieldCostGame.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCostGame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCostGame.setText("0");
        jTextFieldCostGame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldCostGame.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldCostGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCostGameActionPerformed(evt);
            }
        });
        jPanel14.add(jTextFieldCostGame);

        jLabelCostAccesories.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabelCostAccesories.setText("Cost of Accesories");
        jPanel14.add(jLabelCostAccesories);

        jTextFieldCostAccesories.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCostAccesories.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCostAccesories.setText("0");
        jTextFieldCostAccesories.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldCostAccesories.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextFieldCostAccesories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCostAccesoriesActionPerformed(evt);
            }
        });
        jPanel14.add(jTextFieldCostAccesories);

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 350, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldXboxOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldXboxOneActionPerformed
       
           
    }//GEN-LAST:event_jTextFieldXboxOneActionPerformed

    private void jCheckBoxXboxOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxXboxOneActionPerformed
        double cXboxOne = Double.parseDouble(jTextFieldCostConsole.getText());
       double XboxOne = Double.parseDouble(jTextFieldXboxOne.getText());
       double iXboxOne = 299.99;
       
       if (jCheckBoxXboxOne.isSelected())
       {
       i[0] = (XboxOne * iXboxOne) + cXboxOne;
       String pConsole = String.format("%.2f", i[0]);
       jTextFieldCostConsole.setText(pConsole);
       //jTextFieldXboxOne.setText(pConsole);
       }
    }//GEN-LAST:event_jCheckBoxXboxOneActionPerformed

    private void jTextFieldSteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSteamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSteamActionPerformed

    private void jTextFieldPS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPS4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPS4ActionPerformed

    private void jTextFieldWiiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWiiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWiiActionPerformed

    private void jTextFieldGamecubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGamecubeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGamecubeActionPerformed

    private void jCheckBoxPS4ControllerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPS4ControllerActionPerformed
        double cPS4 = Double.parseDouble(jTextFieldCostAccesories.getText());
       double PS4 = Double.parseDouble(jTextFieldPS4Controller.getText());
       double iPS4 = 12.00;
       
       if (jCheckBoxPS4Controller.isSelected())
       {
       i[14] = (PS4 * iPS4) + cPS4;
       String pAccesory = String.format("%.2f", i[14]);
       jTextFieldCostAccesories.setText(pAccesory);
    } 
    }//GEN-LAST:event_jCheckBoxPS4ControllerActionPerformed

    private void jCheckBoxWiiuGamepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWiiuGamepadActionPerformed
        double cWii = Double.parseDouble(jTextFieldCostAccesories.getText());
       double Wii = Double.parseDouble(jTextFieldWiiugamepad.getText());
       double iWii = 60.00;
       
       if (jCheckBoxWiiuGamepad.isSelected())
       {
       i[15] = (Wii * iWii) + cWii;
       String pAccesory = String.format("%.2f", i[15]);
       jTextFieldCostAccesories.setText(pAccesory);
    } 
    }//GEN-LAST:event_jCheckBoxWiiuGamepadActionPerformed

    private void jTextFieldPS4ControllerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPS4ControllerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPS4ControllerActionPerformed

    private void jTextFieldgamecubecontrollerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldgamecubecontrollerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldgamecubecontrollerActionPerformed

    private void jTextFieldWiiugamepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWiiugamepadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWiiugamepadActionPerformed

    private void jTextFieldHeadsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHeadsetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHeadsetActionPerformed

    private void jTextFieldxboxcontrollerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldxboxcontrollerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldxboxcontrollerActionPerformed

    private void jTextFieldMaddenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaddenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaddenActionPerformed

    private void jCheckBoxIWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxIWActionPerformed
       double cIW = Double.parseDouble(jTextFieldCostGame.getText());
       double IW = Double.parseDouble(jTextFieldWarfare.getText());
       double iIW = 30.00;
       
       if (jCheckBoxIW.isSelected())
       {
       i[8] = (IW * iIW) + cIW;
       String pGame = String.format("%.2f", i[8]);
       jTextFieldCostGame.setText(pGame);
    }   
    }//GEN-LAST:event_jCheckBoxIWActionPerformed

    private void jTextFieldWarfareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWarfareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWarfareActionPerformed

    private void jCheckBoxWatchDogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWatchDogsActionPerformed
        double cDog = Double.parseDouble(jTextFieldCostGame.getText());
       double Dog = Double.parseDouble(jTextFieldWatchDog.getText());
       double iDog = 40.00;
       
       if (jCheckBoxWatchDogs.isSelected())
       {
       i[9] = (Dog * iDog) + cDog;
       String pGame = String.format("%.2f", i[9]);
       jTextFieldCostGame.setText(pGame);
    }   
    }//GEN-LAST:event_jCheckBoxWatchDogsActionPerformed

    private void jTextFieldWatchDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWatchDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWatchDogActionPerformed

    private void jTextFieldMarioKartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMarioKartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMarioKartActionPerformed

    private void jTextFieldDotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDotaActionPerformed

    private void jTextFieldForzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldForzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldForzaActionPerformed

    private void jTextFieldXbox360ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldXbox360ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldXbox360ActionPerformed

    private void jTextFieldPS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPS3ActionPerformed

    private void jTextFieldCostGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCostGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCostGameActionPerformed

    private void jTextFieldCostConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCostConsoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCostConsoleActionPerformed

    private void jTextFieldCostAccesoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCostAccesoriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCostAccesoriesActionPerformed

    private void jTextFieldSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSubTotalActionPerformed

    private void jTextFieldTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTaxActionPerformed

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jTextFieldCostGame.setText("0");
        jTextFieldCostConsole.setText("0");
        jTextFieldCostAccesories.setText("0");
        jTextFieldTax.setText("0");
        jTextFieldTotal.setText("0");
        jTextFieldSubTotal.setText("0");
        jTextFieldPS4.setText("0");
        jTextFieldSteam.setText("0");
        jTextFieldWii.setText("0");
        jTextFieldGamecube.setText("0");
        jTextFieldXbox360.setText("0");
        jTextFieldPS3.setText("0");
        jTextFieldMadden.setText("0");
        jTextFieldWarfare.setText("0");
        jTextFieldWatchDog.setText("0");
        jTextFieldMarioKart.setText("0");
        jTextFieldDota.setText("0");
        jTextFieldForza.setText("0");
        jTextFieldHeadset.setText("0");
        jTextFieldPS4Controller.setText("0");
        jTextFieldWiiugamepad.setText("0");
        jTextFieldgamecubecontroller.setText("0");
        jTextFieldxboxcontroller.setText("0");
        jTextFieldXboxOne.setText("0");
        jCheckBoxXboxOne.setSelected(false);
        jCheckBoxPS4.setSelected(false);
        jCheckBoxSteam.setSelected(false);
        jCheckBoxWiiU.setSelected(false);
        jCheckBoxGamecube.setSelected(false);
        jCheckBoxXbox360.setSelected(false);
        jCheckBoxPS3.setSelected(false);
        jCheckBoxMadden.setSelected(false);
        jCheckBoxIW.setSelected(false);
        jCheckBoxWatchDogs.setSelected(false);
        jCheckBoxMarioKart.setSelected(false);
        jCheckBoxDota.setSelected(false);
        jCheckBoxForza.setSelected(false);
        jCheckBoxHeadset.setSelected(false);
        jCheckBoxPS4Controller.setSelected(false);
        jCheckBoxWiiuGamepad.setSelected(false);
        jCheckBoxGamecubeController.setSelected(false);
        jCheckBoxXboxOneController.setSelected(false);
        jTextAreaReceipt.setText(null);
        
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceiptActionPerformed
        console[0]= Double.parseDouble(jTextFieldXboxOne.getText());
        console[1]= Double.parseDouble(jTextFieldPS4.getText());
        console[2]= Double.parseDouble(jTextFieldSteam.getText());
        console[3]= Double.parseDouble(jTextFieldWii.getText());
        console[4]= Double.parseDouble(jTextFieldGamecube.getText());
        console[5]= Double.parseDouble(jTextFieldXbox360.getText());
        console[6]= Double.parseDouble(jTextFieldPS3.getText());
        
        game[0]= Double.parseDouble(jTextFieldMadden.getText());
        game[1]= Double.parseDouble(jTextFieldWarfare.getText());
        game[2]= Double.parseDouble(jTextFieldWatchDog.getText());
        game[3]= Double.parseDouble(jTextFieldMarioKart.getText());
        game[4]= Double.parseDouble(jTextFieldDota.getText());
        game[5]= Double.parseDouble(jTextFieldForza.getText());
        
        accesory[0]= Double.parseDouble(jTextFieldHeadset.getText());
        accesory[1]= Double.parseDouble(jTextFieldPS4Controller.getText());
        accesory[2]= Double.parseDouble(jTextFieldWiiugamepad.getText());
        accesory[3]= Double.parseDouble(jTextFieldgamecubecontroller.getText());
        accesory[4]= Double.parseDouble(jTextFieldxboxcontroller.getText());
        
        
        
        cost[0]= String.valueOf(jTextFieldTax.getText());
        cost[1]= String.valueOf(jTextFieldSubTotal.getText());
        cost[2]= String.valueOf(jTextFieldTotal.getText());
        
        int reference;
        reference = 1325 + (int) (Math.random()*4238);
        //int refs = (reference);
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("MM-dd-yyyy");
        Tdate.format(timer.getTime());
        
        
        
        
        
        jTextAreaReceipt.append(" \t\n Nicks Game Shop: \n\n"+
                "Reciept Number: " + reference +
                "\nDate: " + Tdate.format(timer.getTime()) +
                " Time: " + tTime.format(timer.getTime()) +
                "\n-------------Consoles---------------"+
               "\nXbox One: " + console[0] + 
                "\nPS4: " + console[1] + 
                "\nSteam Box: " + console[2] + 
                "\nWii U: " + console[3] + 
                "\nGamecube: " + console[4] +
                "\nXbox 360: " + console[5] + 
                "\nPS3: " + console[6] + 
                "\n-------------Games-------------"+
                "\nMadden 17 Xbox One: " + game[0] + 
                "\nCall of Duty:Infinite Warfare PS4: " + game[1] + 
                "\nWatch Dogs Wii U: " + game[2] + 
                "\nMario Kart Gamecube: " + game[3] + 
                "\nDota 2: " + game[4] + 
                "\nForza 3 Xbox One: " + game[5] + 
                "\n-------------Accesories-------------"+
                "\nTurtle Beach Headset: " + accesory[0] + 
                "\nPS4 Controller: " + accesory[1] + 
                "\nWii U Gamepad: " + accesory[2] + 
                "\nGamecube Controller: " + accesory[3] + 
                "\nXbox One Controller: " + accesory[4] + 
                "\n--------------------------------"+
                "\nTax: " + cost[0] + 
                "\nSub-Total: " + cost[1] + 
                "\nTotal: " + cost[2] + 
                "\n--------------------------------"+
                "\n\nThank You! See You Soon!");

    }//GEN-LAST:event_jButtonReceiptActionPerformed

    private void jCheckBoxPS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPS4ActionPerformed
//not used
    }//GEN-LAST:event_jCheckBoxPS4ActionPerformed

    private void jCheckBoxPS4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxPS4MouseClicked
         double cPS4 = Double.parseDouble(jTextFieldCostConsole.getText());
       double PS4 = Double.parseDouble(jTextFieldPS4.getText());
       double iPS4 = 249.99;
       
       if (jCheckBoxPS4.isSelected())
       {
       i[1] = (PS4 * iPS4) + cPS4;
       String pConsole = String.format("%.2f", i[1]);
       jTextFieldCostConsole.setText(pConsole);
       //jTextFieldPS4.setText(pConsole);
       }
    }//GEN-LAST:event_jCheckBoxPS4MouseClicked

    private void jCheckBoxSteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSteamActionPerformed
         double cSteam = Double.parseDouble(jTextFieldCostConsole.getText());
       double Steam = Double.parseDouble(jTextFieldSteam.getText());
       double iSteam = 59.99;
       
       if (jCheckBoxSteam.isSelected())
       {
       i[2] = (Steam * iSteam) + cSteam;
       String pConsole = String.format("%.2f", i[2]);
       jTextFieldCostConsole.setText(pConsole);
       //jTextFieldSteam.setText(pConsole);
       }
    }//GEN-LAST:event_jCheckBoxSteamActionPerformed

    private void jCheckBoxWiiUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWiiUActionPerformed
         double cWii = Double.parseDouble(jTextFieldCostConsole.getText());
       double Wii = Double.parseDouble(jTextFieldWii.getText());
       double iWii = 149.99;
       
       if (jCheckBoxWiiU.isSelected())
       {
       i[3] = (Wii * iWii) + cWii;
       String pConsole = String.format("%.2f", i[3]);
       jTextFieldCostConsole.setText(pConsole);
       //jTextFieldWii.setText(pConsole);
       }
    }//GEN-LAST:event_jCheckBoxWiiUActionPerformed

    private void jCheckBoxGamecubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGamecubeActionPerformed
         double cGC = Double.parseDouble(jTextFieldCostConsole.getText());
       double GC = Double.parseDouble(jTextFieldGamecube.getText());
       double iGC = 39.99;
       
       if (jCheckBoxGamecube.isSelected())
       {
       i[4] = (GC * iGC) + cGC;
       String pConsole = String.format("%.2f", i[4]);
       jTextFieldCostConsole.setText(pConsole);
      // jTextFieldGamecube.setText(pConsole);
       }
    }//GEN-LAST:event_jCheckBoxGamecubeActionPerformed

    private void jCheckBoxXbox360ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxXbox360ActionPerformed
         double cx360 = Double.parseDouble(jTextFieldCostConsole.getText());
       double x360 = Double.parseDouble(jTextFieldXbox360.getText());
       double ix360 = 99.99;
       
       if (jCheckBoxXbox360.isSelected())
       {
       i[5] = (x360 * ix360) + cx360;
       String pConsole = String.format("%.2f", i[5]);
       jTextFieldCostConsole.setText(pConsole);
      // jTextFieldXbox360.setText(pConsole);
       }
    }//GEN-LAST:event_jCheckBoxXbox360ActionPerformed

    private void jCheckBoxPS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPS3ActionPerformed
         double cPS3 = Double.parseDouble(jTextFieldCostConsole.getText());
       double PS3 = Double.parseDouble(jTextFieldPS3.getText());
       double iPS3 = 125.00;
       
       if (jCheckBoxPS3.isSelected())
       {
       i[6] = (PS3 * iPS3) + cPS3;
       String pConsole = String.format("%.2f", i[6]);
       jTextFieldCostConsole.setText(pConsole);
      // jTextFieldPS3.setText(pConsole);
       }
    }//GEN-LAST:event_jCheckBoxPS3ActionPerformed

    private void jCheckBoxMaddenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMaddenActionPerformed
       double cMadden = Double.parseDouble(jTextFieldCostGame.getText());
       double Madden = Double.parseDouble(jTextFieldMadden.getText());
       double iMadden = 25.00;
       
       if (jCheckBoxMadden.isSelected())
       {
       i[7] = (Madden * iMadden) + cMadden;
       String pGame = String.format("%.2f", i[7]);
       jTextFieldCostGame.setText(pGame);}
    }//GEN-LAST:event_jCheckBoxMaddenActionPerformed

    private void jCheckBoxMarioKartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMarioKartActionPerformed
        double cMario = Double.parseDouble(jTextFieldCostGame.getText());
       double Mario = Double.parseDouble(jTextFieldMarioKart.getText());
       double iMario = 25.00;
       
       if (jCheckBoxMarioKart.isSelected())
       {
       i[10] = (Mario * iMario) + cMario;
       String pGame = String.format("%.2f", i[10]);
       jTextFieldCostGame.setText(pGame);
    }   
    }//GEN-LAST:event_jCheckBoxMarioKartActionPerformed

    private void jCheckBoxDotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDotaActionPerformed
        double cDota = Double.parseDouble(jTextFieldCostGame.getText());
       double Dota = Double.parseDouble(jTextFieldDota.getText());
       double iDota = 100.00;
       
       if (jCheckBoxDota.isSelected())
       {
       i[11] = (Dota * iDota) + cDota;
       String pGame = String.format("%.2f", i[11]);
       jTextFieldCostGame.setText(pGame);
    }   
    }//GEN-LAST:event_jCheckBoxDotaActionPerformed

    private void jCheckBoxForzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxForzaActionPerformed
        double cForza = Double.parseDouble(jTextFieldCostGame.getText());
       double Forza = Double.parseDouble(jTextFieldForza.getText());
       double iForza = 10.00;
       
       if (jCheckBoxForza.isSelected())
       {
       i[12] = (Forza * iForza) + cForza;
       String pGame = String.format("%.2f", i[12]);
       jTextFieldCostGame.setText(pGame);
    }   
    }//GEN-LAST:event_jCheckBoxForzaActionPerformed

    private void jCheckBoxHeadsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHeadsetActionPerformed
        double cHeadset = Double.parseDouble(jTextFieldCostAccesories.getText());
       double Headset = Double.parseDouble(jTextFieldHeadset.getText());
       double iHeadset = 25.00;
       
       if (jCheckBoxHeadset.isSelected())
       {
       i[13] = (Headset * iHeadset) + cHeadset;
       String pAccesory = String.format("%.2f", i[13]);
       jTextFieldCostAccesories.setText(pAccesory);
    }   
    }//GEN-LAST:event_jCheckBoxHeadsetActionPerformed

    private void jCheckBoxGamecubeControllerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGamecubeControllerActionPerformed
        double cGamecubeController = Double.parseDouble(jTextFieldCostAccesories.getText());
       double GamecubeController = Double.parseDouble(jTextFieldgamecubecontroller.getText());
       double iGamecubeController = 99.00;
       
       if (jCheckBoxGamecubeController.isSelected())
       {
       i[16] = (GamecubeController * iGamecubeController) + cGamecubeController;
       String pAccesory = String.format("%.2f", i[16]);
       jTextFieldCostAccesories.setText(pAccesory);
    } 
    }//GEN-LAST:event_jCheckBoxGamecubeControllerActionPerformed

    private void jCheckBoxXboxOneControllerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxXboxOneControllerActionPerformed
         double cXboxController = Double.parseDouble(jTextFieldCostAccesories.getText());
       double XboxController = Double.parseDouble(jTextFieldxboxcontroller.getText());
       double iXboxController = 75.00;
       
       if (jCheckBoxXboxOneController.isSelected())
       {
       i[17] = (XboxController * iXboxController) + cXboxController;
       String pAccesory = String.format("%.2f", i[17]);
       jTextFieldCostAccesories.setText(pAccesory);
    } 
    }//GEN-LAST:event_jCheckBoxXboxOneControllerActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButtonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTotalActionPerformed
        game[0] = Double.parseDouble(jTextFieldCostConsole.getText());
        game[1] = Double.parseDouble(jTextFieldCostGame.getText());
        game[2] = Double.parseDouble(jTextFieldCostAccesories.getText());
        
        double cTotal1 = (game[0]+game[1]+game[2]);
        
        String iTaxTotal = String.format ("$%.2f", cTotal1 / 100);
        jTextFieldTax.setText(iTaxTotal);
        
        double SubTotal = (cTotal1);
        String iSubTotal = String.format("$%.2f", SubTotal);
        jTextFieldSubTotal.setText(iSubTotal);
        
        double allTotal = (cTotal1);
        String iTotal = String.format("$%.2f", allTotal + (allTotal/100));
        jTextFieldTotal.setText(iTotal);
        
        String CostG = String.format("$%.2f", game[0]);
        jTextFieldCostGame.setText(CostG);
        
         String CostC = String.format("$%.2f", game[1]);
        jTextFieldCostConsole.setText(CostC);
        
         String CostA = String.format("$%.2f", game[2]);
        jTextFieldCostAccesories.setText(CostA);
    }//GEN-LAST:event_jButtonTotalActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
      
         try{
            boolean complete = jTextAreaReceipt.print();
            //The above line reads the error "Add argument to match print(Graphics)"
            if(complete){
                JOptionPane.showMessageDialog(null,  "Printjob Finished", "Report", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Printing", "Printer", JOptionPane.ERROR_MESSAGE);
                }
            }catch(PrinterException e){JOptionPane.showMessageDialog(null, e);
            }
        

  
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButtonJukeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJukeBoxActionPerformed
       /* String soundName = "yourSound.wav";    
AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile());
Clip clip = AudioSystem.getClip();
clip.open(audioInputStream);
clip.start();*/
        
     playSound("eightiesJam.wav");
       
       
       
       
   
            
       
    }//GEN-LAST:event_jButtonJukeBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Video_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Video_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Video_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Video_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Video_Management_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonJukeBox;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonReceipt;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonTotal;
    private javax.swing.JCheckBox jCheckBoxDota;
    private javax.swing.JCheckBox jCheckBoxForza;
    private javax.swing.JCheckBox jCheckBoxGamecube;
    private javax.swing.JCheckBox jCheckBoxGamecubeController;
    private javax.swing.JCheckBox jCheckBoxHeadset;
    private javax.swing.JCheckBox jCheckBoxIW;
    private javax.swing.JCheckBox jCheckBoxMadden;
    private javax.swing.JCheckBox jCheckBoxMarioKart;
    private javax.swing.JCheckBox jCheckBoxPS3;
    private javax.swing.JCheckBox jCheckBoxPS4;
    private javax.swing.JCheckBox jCheckBoxPS4Controller;
    private javax.swing.JCheckBox jCheckBoxSteam;
    private javax.swing.JCheckBox jCheckBoxWatchDogs;
    private javax.swing.JCheckBox jCheckBoxWiiU;
    private javax.swing.JCheckBox jCheckBoxWiiuGamepad;
    private javax.swing.JCheckBox jCheckBoxXbox360;
    private javax.swing.JCheckBox jCheckBoxXboxOne;
    private javax.swing.JCheckBox jCheckBoxXboxOneController;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCostAccesories;
    private javax.swing.JLabel jLabelCostConsole;
    private javax.swing.JLabel jLabelCostGame;
    private javax.swing.JLabel jLabelSubTotal;
    private javax.swing.JLabel jLabelTax;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaReceipt;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldCostAccesories;
    private javax.swing.JTextField jTextFieldCostConsole;
    private javax.swing.JTextField jTextFieldCostGame;
    private javax.swing.JTextField jTextFieldDota;
    private javax.swing.JTextField jTextFieldForza;
    private javax.swing.JTextField jTextFieldGamecube;
    private javax.swing.JTextField jTextFieldHeadset;
    private javax.swing.JTextField jTextFieldMadden;
    private javax.swing.JTextField jTextFieldMarioKart;
    private javax.swing.JTextField jTextFieldPS3;
    private javax.swing.JTextField jTextFieldPS4;
    private javax.swing.JTextField jTextFieldPS4Controller;
    private javax.swing.JTextField jTextFieldSteam;
    private javax.swing.JTextField jTextFieldSubTotal;
    private javax.swing.JTextField jTextFieldTax;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldWarfare;
    private javax.swing.JTextField jTextFieldWatchDog;
    private javax.swing.JTextField jTextFieldWii;
    private javax.swing.JTextField jTextFieldWiiugamepad;
    private javax.swing.JTextField jTextFieldXbox360;
    private javax.swing.JTextField jTextFieldXboxOne;
    private javax.swing.JTextField jTextFieldgamecubecontroller;
    private javax.swing.JTextField jTextFieldxboxcontroller;
    // End of variables declaration//GEN-END:variables
}
